name: Run Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman-collections/CollectionKasirAja.postman_collection.json \
            --env-var "baseUrl=${{ secrets.BASE_URL }}" \
            --env-var "username=${{ secrets.USERNAME }}" \
            --env-var "password=${{ secrets.PASSWORD }}"